" settings
syntax on
set viminfo+=n~/.vim/.viminfo
set hlsearch
set wildmenu
set ts=8 sts=0 et sta sw=2

" keymaps
map <C-n> :bn<CR>
map <C-p> :bp<CR>

" colorscheme
let g:gruvbox_italic = 1
let g:gruvbox_contrast_dark = "hard"
let g:gruvbox_contrast_light = "soft"
set bg=dark
" set bg=light
colorscheme gruvbox

" status line
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1
